### ISSUE TITLE
juepark & yoyoo 요유 버전 백엔드로 카카오 로그인만 시험해보기

### ISSUE THREAD

**Issue by echoja** [Mapps-unit/backend-v2#3]
- #2 선행되어야 함.

**Comment by Yoowatney** [comment]
카카오 로그인 시험이 아니라 로컬 로그인 시험인거죠?

**Comment by maaps-unit** [comment]
> 카카오 로그인 시험이 아니라 로컬 로그인 시험인거죠?

노우 그 우리 auth kakao login 테스트 해봣잖아요 ㅋㅋ

**Comment by Yoowatney** [comment]
아까 지하철에선 안 됐었는데 집와서 다시 해보니 정상 작동하네요..

**Comment by Yoowatney** [comment]
일단 카카오 로그인 정상작동까지 시켰는데 그동안 삽질했던 부분들 정리합니다

1. invalid grant error KOE303
Url searchParam append 메서드 인자에 '/' 같은 특수문자가 들어가면 %aF로 바뀌어 append되어 invalid grant 오류가 납니다
이 부분은 Yekim님이 하신거처럼 +=를 통해 해결해주었습니다

2. TypeError: Cannot read property 'findOne' of undefined 에러
route.js에서 User를 콘솔로그로 찍어봤을 때 undefined가 나옵니다
이 때문에 fideOne이란 속성값을 못 읽는다고 에러메시지가 나온거 같습니다 
require 확인 했고 user 경로도 확인해줬는데 계속 같은 에러가 나오네요
app.js에서는 User를 인식하고 있길래 app.js로 kakao 로그인 코드를 몰아넣었더니 로그인은 일단 해결됐습니다만, 왜 User를 못 찾는지 원인을 모르겠습니다
